# Generated by Django 3.0.2 on 2020-02-09 02:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('value', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('influence', models.DecimalField(decimal_places=2, max_digits=8)),
                ('group', models.IntegerField()),
                ('attributes', models.ManyToManyField(to='core_module.Attribute')),
            ],
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.DecimalField(decimal_places=2, max_digits=8)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cvor1', to='core_module.Node')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cvor2', to='core_module.Node')),
            ],
        ),
    ]
