# Generated by Django 3.0.2 on 2020-02-10 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_module', '0002_auto_20200209_1640'),
    ]

    operations = [
        migrations.AddField(
            model_name='attribute',
            name='node_id',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
    ]
